import { API_BASE } from './backend'

async function post(path, body) {
  const res = await fetch(`${API_BASE}${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: body !== undefined ? JSON.stringify(body) : undefined,
  })
  const json = await res.json().catch(() => null)
  if (!res.ok) throw new Error(json?.error || `${res.status} ${res.statusText}`)
  return json
}

// ── Actuation toggle ─────────────────────────────────────────────
// enabled=true  → autopilot actively scales services
// enabled=false → autopilot reasons but sends no commands (freeze)
export const setActuation = (enabled) =>
  post('/control/toggle', { enabled })

// ── Policy presets ────────────────────────────────────────────────
// 'aggressive'   → fast scaling, high risk tolerance
// 'conservative' → slow scaling, low risk tolerance (safe mode)
// 'balanced'     → default middle ground
export const setPolicy = (preset) =>
  post('/policy/update', { preset })

// ── Force single engine tick ──────────────────────────────────────
// Manually advance the control loop one step.
// Useful when inspecting state or debugging.
export const stepOnce = () =>
  post('/runtime/step')

// ── Simulate traffic stress on a service ─────────────────────────
// service_id: which service to stress (or null for all)
// duration_ticks: how many engine ticks to apply it (1 tick ≈ 2s)
// request_factor: multiply arrival rate by this (e.g. 3 = 3× traffic)
// latency_factor: multiply latency by this (e.g. 2 = double latency)
export const runStressTest = (serviceId, durationTicks, requestFactor, latencyFactor) =>
  post('/control/chaos-run', {
    service_id:     serviceId || '',
    duration_ticks: durationTicks || 20,
    request_factor: requestFactor || 2.5,
    latency_factor: latencyFactor || 1.6,
  })

// ── Replay a traffic burst on a service ──────────────────────────
// Applies a sudden spike (factor × normal traffic) for duration_ticks.
// Different from stress test: this is a clean spike, not degraded traffic.
export const replayBurst = (serviceId, durationTicks, factor) =>
  post('/control/replay-burst', {
    service_id:     serviceId || '',
    duration_ticks: durationTicks || 20,
    factor:         factor || 2.0,
  })

// ── Trigger sandbox experiment ────────────────────────────────────
// Runs the engine's internal sandbox with an autogenerated experiment.
export const triggerSandbox = (type, durationTicks) =>
  post('/sandbox/trigger', {
    type:           type || 'experiment',
    duration_ticks: durationTicks || 10,
  })

// ── Simulation control ────────────────────────────────────────────
// action: 'run'|'reset'
// Forces the Monte Carlo simulation stage for N ticks.
export const controlSimulation = (action, durationTicks) =>
  post('/simulation/control', {
    action:         action || 'run',
    duration_ticks: durationTicks || 10,
  })

// ── Intelligence rollout ──────────────────────────────────────────
// Triggers the RL/autopilot policy evaluation for N ticks.
// This lets the intelligence layer re-assess and update its model.
export const triggerRollout = (durationTicks) =>
  post('/intelligence/rollout', { duration_ticks: durationTicks || 10 })

// ── Acknowledge alert ─────────────────────────────────────────────
export const ackAlert = (alertId) =>
  post('/alerts/ack', { alert_id: alertId })